python main.py \
--device=gpus \
--gpus=0 \
--model-type=rnn \
--model=MyRNN \
--model-version=11 \
--dataset=TimeMachine \
--train-bsz=32 \
--test-bsz=32 \
--lr=1 \
--lr-decay=0 \
--optim=SGD \
--epochs=500
