python main.py \
--device=gpus \
--gpus=0 \
--model-type=cnn \
--num-step=128 \
--model=CNN \
--model-version=11 \
--dataset=CIFAR100 \
--train-bsz=128 \
--test-bsz=128 \
--lr=0.01 \
--lr-decay=1 \
--optim=SGD \
--epochs=100
